Maria m Creación de Imagen controlador
francomatuz/Salud_webapp pull request #12
Opened 2023-11-23 17:26 UTC by maryymullins777

Hola buenos días hice sobre imagen controlador  

también otros cambios en la imagen servicio que son la validación del tipo de archivo, generar nombre único de la imagen y actualización de una imagen se realice de manera segura y con un identificador de imagen válido, evitando posibles problemas causados por IDs nulos. 

Si algo esta mal o fallando por favor deseo que me expliquen por favor para evitar retrasar este proyecto y ser un apoyo para el mismo. 
Gracias por su Atención

2023-11-23 20:34 UTC, francomatuz requested changes

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +        Long imagenId = imagenServicio.guardarImagen(file);
Este servicio está incompleto. Revisar llamados

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen guardar(MultipartFile archivo) throws MiException {
Tener consistencia en los nombres de las variables

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +            } catch (Exception e) {
Utilizar las exceptions  ya creadas

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        return null;
Deberia retornar una imagen, no un null, siguiendo la logica del codigo escrito

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen actualizar(MultipartFile archivo, String idImagen) throws MiException {
Los "id" no son strings

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +                        imagen = respuesta.get();
La variable imagen, no debe ser creada

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +                String nombreUnico = UUID.randomUUID().toString() + "_" + archivo.getOriginalFilename();
No se debe crear un registro nuevo, se debe actualizar el existente

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +
Este codigo va a dar error si cualquiera de los atributos vienen en "null". Investigar sobre : sentencias ternarias o en su defecto utilizar condicionales

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Long guardarImagen(MultipartFile file) {
Esto esta vacio

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @GenericGenerator(name = "uuid", strategy = "uuid2")
Estamos utilizando otro generador de "id" mantener la consistencia en el proyecto

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @Lob
Aclarar que es esto

2023-11-23 20:34 UTC, francomatuz commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @Basic(fetch = FetchType.LAZY)
falta constructores

2023-11-24 06:53 UTC, maryymullins777 reviewed
Hola realice las correcciones 
Si algo esta mal si necesitaría ayuda de alguien mas por favor para no retrasar lo del proyecto

2023-11-24 18:50 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @Basic(fetch = FetchType.LAZY)
hola 
ya realice para que me puedan corregir please

2023-11-24 18:50 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @Lob
hola 
ya realice para que me puedan corregir please

2023-11-24 18:51 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @GenericGenerator(name = "uuid", strategy = "uuid2")
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:51 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Long guardarImagen(MultipartFile file) {
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:51 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:52 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen actualizar(MultipartFile archivo, String idImagen) throws MiException {
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:52 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        return null;
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:52 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +            } catch (Exception e) {
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:52 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen guardar(MultipartFile archivo) throws MiException {
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-24 18:52 UTC, maryymullins777 commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +        Long imagenId = imagenServicio.guardarImagen(file);
Hola creo que ya le hice el mismo pero necesito si  me puedan corregir please

2023-11-27 12:48 UTC, slopezalvas requested changes

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +            return ResponseEntity.badRequest().body("Error al cargar la imagen: " + e.getMessage());
utilizar try/catch solo en servicios

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +        } catch (Exception e) {
sacar el try/catch

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +            return ResponseEntity.badRequest().body("Error al actualizar la imagen: " + e.getMessage());
sacar el try/catch

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/controladores/ImagenControlador.java
> +        } catch (Exception e) {
sacar el try/catch

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/controladores/PacienteControlador.java
> +        } catch (IOException e) {
sacar el try/catch

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public void actualizarImagen(Long id, MultipartFile archivo) throws IOException {
cambiar IOException a MiException

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        Paciente paciente = pacienteServicio.obtenerPacientePorId(idPaciente);
verificar que la respuesta no sea null (si es null: tirar una exception, sino: continuar)

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        Profesional profesional = profesionalServicio.obtenerProfesionalPorId(idProfesional);
verificar que la respuesta no sea null (si es null: tirar una exception, sino: continuar)

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen cargarImagen(byte[] imageData) {
este metodo si no se usa esta de mas

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        Optional<Imagen> optionalImagen = imagenRepositorio.findById(id);
sacar "optional"

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        return optionalImagen.map(Imagen::getData).orElse(null);
verificar que la respuesta no sea null (si es null: tirar una exception, sino: continuar)

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +            imagen.setData(archivo.getBytes());
verificar que archivo.Bytes se a distinto a imagen.Data, si es distinto cambiar, si no ignorar.  tambien puede venir null archivo.Bytes agregar verificacion

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +            imagenRepositorio.save(imagen);
no se le puede actualizar ningun otro atributo como el nombre por ejemplo?

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        imagenRepositorio.deleteById(id);
esto borra de la db la imagen, implementar SoftDelete (borrado logico)

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +        return imagenRepositorio.save(imagen);
sigue sin retornar la imagen, el metodo save es de tipo void

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/PacienteServicio.java
> +        Optional<Paciente> pacienteOptional = pacienteRepositorio.buscarPorId(id);
quitar optional

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    private Paciente paciente;
no es necesario que tenga el atributo paciente

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    @OneToOne(mappedBy = "imagen", cascade = CascadeType.ALL)
no es necesario que tenga el atributo profesional

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +
no se guarda el nombre de la imagen en la db

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Imagen.java
> +    public void setId(Long id) {
borrar setId, nunca se va a usar

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Paciente.java
> +    @JoinColumn(name = "imagen_id")
no es necesario que tenga imagen, si esta planteado dentro del proyecto la relacion deberia der de uno a muchos

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Paciente.java
> +    public void setId(Long id) {
setId no se usa nunca, borrarlo

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Paciente.java
> +    public void setImagen(Imagen imagen) {
no va a funcionar, resolver

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Paciente.java
> +    public Imagen getImagen() {
no va a funcionar, resolver

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Profesional.java
> +    private Imagen imagen;
no es necesario que tenga imagen, si esta planteado dentro del proyecto la relacion deberia der de uno a muchos

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Profesional.java
> +    public Imagen getImagen() {
estos dos metodos van a romper, verificar la logica con el servicio de imagen

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Usuario.java
> +    public Imagen getImagen() {
sacar

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/entidades/Usuario.java
> +    public void setImagen(Imagen imagen) {
sacar

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen guardarImagen(MultipartFile archivo, Long idPaciente, Long idProfesional) throws IOException {
o tiene idPaciente o tiene idProfesional, no puede tener ambos, revisar el requerimiento

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ImagenServicio.java
> +    public Imagen guardarImagen(MultipartFile archivo, Long idPaciente, Long idProfesional) throws IOException {
utilizar MiException y try/catch

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/PacienteServicio.java
>      @Autowired
No tocar el servicio de paciente, solo hacer lo que pide la tarea.

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/ProfesionalServicio.java
>      @Autowired
No tocar el servicio de profesional, solo hacer lo que pide la tarea.

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/PacienteServicio.java
> +    public Paciente obtenerPaciente(Long pacienteId) {
borrar metodos vacios

2023-11-27 12:48 UTC, slopezalvas commented on src/main/java/com/egg/salud_webapp/servicios/PacienteServicio.java
> +    public void guardarPaciente(Paciente paciente) {
borrar metodos vacios

2023-12-04 00:05 UTC, closed without merging